name: Cypress Tests (Chrome Only)
on:
  push:
    branches: [dev, main]
  pull_request:
  workflow_dispatch:

jobs:
  cypress-chrome:
    name: Cypress Tests - Chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Check dependencies cache
        id: cache-node-modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json', 'package.json') }}
      
      - name: Install Project dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        shell: bash
        run: npm install --no-workspaces
      
      - name: Start server in the background
        run: npm run dev &
      
      - name: Run Smoke Tests (Dev Branch)
        if: github.ref == 'refs/heads/dev'
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          working-directory: CYPRESSTEST
          browser: chrome
          headed: true
        env:
          grepTags: '@smoke'
      
      - name: Run Full Regression Tests (Main Branch)
        if: github.ref == 'refs/heads/main'
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          working-directory: CYPRESSTEST
          browser: chrome
          headed: true
      
      - name: Clean up test artifacts
        if: always()
        run: |
          echo "Cleaning up test artifacts..."
          rm -rf CYPRESSTEST/cypress/screenshots
          rm -rf CYPRESSTEST/cypress/videos  
          rm -rf CYPRESSTEST/cypress/reports
          echo "Cleanup completed"